version: '3.8'
services:
  ethos_app:
    build: .
    container_name: ethos_container
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
