services:
  - type: web
    name: ethos-hub-docker
    runtime: docker
    plan: free
    repo: https://github.com/Aryavvij/Ethos-Hub
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
