services:
  - type: web
    name: ethos-hub-docker
    runtime: docker
    plan: free 
    repo: https://github.com/Aryavvij/Ethos-Hub/tree/main
    envVars:
      - key: DATABASE_URL
        sync: false
